apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ohpu
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0052-tenant/tkrw-pr712-0075-0052-app/devfile-sample-ohpu@sha256:fe88088948b77cdb94c2716c4aaf8fec0dd0d6b6ae74fc254b74d846f7a3fb7b
        name: my-nodejs
        resources: {}
status: {}
